### ISSUE TITLE
local Run checks with tox

### ISSUE THREAD

**Issue by EvaJanouskova** [UCL/TLOmodel#1561]
Every time I fetch the master branch, I need to delete the tag 'prof1', otherwise I'm unable to run checks with tox locally.

Could this be fixed, please? It would make things much easier for me.

This is how it looks like if I do not delete the tag 'prof1':
```
/home/eva/anaconda3/envs/TLOmodel/bin/python /usr/share/jetbrains/pycharm-community/plugins/python-ce/helpers/pycharm/_jb_tox_runner.py -e check 
Testing started at 22:22 ...
.pkg: _optional_hooks> python /home/eva/anaconda3/envs/TLOmodel/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/eva/anaconda3/envs/TLOmodel/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
check: packaging backend failed (code=1), with AssertionError: 
/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/version.py:102: UserWarning: tag 'prof1' no version found
  warnings.warn(f"tag {tag!r} no version found")
Traceback (most recent call last):
  File "/home/eva/anaconda3/envs/TLOmodel/lib/python3.11/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/anaconda3/envs/TLOmodel/lib/python3.11/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 328, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 146, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/dist.py", line 307, in __init__
    _Distribution.__init__(self, dist_attrs)
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 284, in __init__
    self.finalize_options()
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools/dist.py", line 659, in finalize_options
    ep(self)
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 123, in infer_version
    _assign_version(dist, config)
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py", line 55, in _assign_version
    maybe_version = _get_version(config, force_write_version_files=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 98, in _get_version
    parsed_version = parse_version(config)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 61, in parse_version
    or parse_scm_version(config)
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_get_version_impl.py", line 40, in parse_scm_version
    return _entrypoints.version_from_entrypoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_entrypoints.py", line 57, in version_from_entrypoint
    maybe_version: version.ScmVersion | None = fn(root, config=config)
                                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/git.py", line 215, in parse
    return _git_parse_inner(
           ^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/git.py", line 259, in _git_parse_inner
    version = version_from_describe(wd, config, describe_command)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/git.py", line 247, in version_from_describe
    return describe_res.parse_success(parse=parse_describe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/_run_cmd.py", line 81, in parse_success
    return parse(self.stdout)
           ^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/git.py", line 245, in parse_describe
    return meta(tag=tag, distance=distance, dirty=dirty, node=node, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/version.py", line 217, in meta
    parsed_version = _parse_tag(tag, preformatted, config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eva/PycharmProjects/TLOmodel/.tox/.pkg/lib/python3.11/site-packages/setuptools_scm/version.py", line 200, in _parse_tag
    assert version is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
Backend: Wrote response {'code': 1, 'exc_type': 'AssertionError', 'exc_msg': ''} to /tmp/pep517_get_requires_for_build_sdist-nt6uomt_.json
.pkg: _exit> python /home/eva/anaconda3/envs/TLOmodel/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta

  check: FAIL code 1 (0.14 seconds)
  evaluation failed :( (0.16 seconds)

Process finished with exit code 1
```

**Comment by tamuri** [comment]
I don't know _why_ that would cause failure - I've removed the tag. Can you `git fetch --all` and try again, please.

**Comment by EvaJanouskova** [comment]
It helped, thanks!

**Comment by matt-graham** [comment]
I _thought_ the issue here was that [`setuptools_scm`](https://setuptools-scm.readthedocs.io), the package we use to automatically set current version from the Git metadata, was confusing `prof1` for a version tag as it was matching the [default regex](https://setuptools-scm.readthedocs.io/en/latest/config/#setuptools_scm._config.DEFAULT_TAG_REGEX) used to find tags corresponding to version releases, but that doesn't seem to be the case, as it would only match tags with initial word segment with dashes used as word separator followed by numeric version identifier (so `prof-1` would be considered a version tag but not `prof1`). Trying the regex against the current tags, it matches `v0.1`, `v0.11` and `v0.2` which is correct. One thing I did notice here though is that `v0.11` is probably misnamed as if this is meant to be an update of `v0.1` this should be `v0.1.1`. As this also points to the same commit as `v0.2` I'm not sure if that is causing issues. Re-opening issue as seems there are some larger problems here even if immediate problem has been resolved

**Comment by tamuri** [comment]
Yes, Tim numbered v0.11 incorrectly, so I asked him to change it to v0.2.

**Comment by matt-graham** [comment]
Assuming it's okay to delete the v0.11 tag then?

**Comment by tamuri** [comment]
Yes, should be - these tags are used on Zenodo, which is still pointing to v0.11 (doesn't show v0.2, presumably because it's the same commit...)

**Comment by matt-graham** [comment]
I've updated the Zenodo record to point to v0.2 tag. Unfortunately we cannot change the actual name of the archive file which includes v0.11 as you can't edit files in a published record, but at least means we can remove tag here safely.
